@BASE_URL = "http://localhost:8080"


### Reset - platform = dev

POST /admin/reset HTTP/1.1
Content-Type: application/json
Host: {{BASE_URL}}

{}

> {%
client.test('Reset users', function() {
  assert.responseHas("responseCode", 200, 'response has 200')
  let json = response.body
  assert.true('ids' in json, 'has .ids')
})
%}

### Reset - platform = nondev

POST /admin/reset HTTP/1.1
Content-Type: application/json
Host: {{BASE_URL}}

{}

> {%
client.test('Reset users', function() {
  assert.responseHas("responseCode", 403, 'response has 200')
})
%}
