@EMAIL = user@test.com
@PASSWORD = asdfasdf

import ./auth.http


### UPDATE_USER

PUT /api/users HTTP/1.1
Content-Type: application/json
Host: {{BASE_URL}}
Authorization: Bearer {{LOGIN.response.body.$.token}}

{
  "email": "{{LOGIN.response.body.$.email}}",
  "password": "{{PASSWORD}}"
}

> {%
   let json = response.body;
   
   client.test('Create user', function () {
   assert.responseHas('responseCode', 200, 'Check response is 200');
   assert.true('id' in json, 'Has .id')
   assert.true('created_at' in json, 'Has .created_at')
   assert.true('updated_at' in json, 'Has .update_at')
   assert.true('email' in json, 'Has .email')
   assert.true(json.email === 'user@test.com', 'Has correct email')
   })
%}
