@EMAIL = user@test.com
@PASSWORD = asdfasdf

import ./admin.http
import ./create-user.http


### UPDATE_USER

run #RESET_USERS
run #CREATE_USER (@PASSWORD=asdfasdf, @EMAIL=user@test.com)

PUT /api/users HTTP/1.1
Content-Type: application/json
Host: {{BASE_URL}}

{
  "email": "{{EMAIL}}",
  "password": "{{PASSWORD}}"
}

> {%
   let json = response.body;
   
   client.test('Create user', function () {
   assert.responseHas('responseCode', 201, 'Check response is 201');
   assert.true('id' in json, 'Has .id')
   assert.true('created_at' in json, 'Has .created_at')
   assert.true('updated_at' in json, 'Has .update_at')
   assert.true('email' in json, 'Has .email')
   assert.true('is_chirpy_red' in json, 'Has .is_chirpy_red')
   assert.true(json.email === 'user@test.com', 'Has correct email')
   })
%}
